import {randomUUID} from 'node:crypto';
import {tool} from 'ai';
import {z} from 'zod';
import {taskDraftSchema,publicProposal,type Snapshot,type Deal,type Customer,type Activity,type Proposal,type ToolEvent} from '../contracts';
import {AppError,draftProposal,summaryOf} from '../domain';
import type {Store} from '../store';
export type Observed={snapshot:Snapshot;deals:Map<string,Deal>;customers:Map<string,Customer>;activities:Map<string,Activity>;detailed:Set<string>;proposals:Map<string,Proposal>};
export function observedContext(snapshot:Snapshot):Observed{return {snapshot,deals:new Map(),customers:new Map(),activities:new Map(),detailed:new Set(),proposals:new Map()};}
export function createTools(store:Store,sessionId:string,runId:string,ctx:Observed,publish:(event:ToolEvent)=>Promise<void>,signal:AbortSignal){
  function observe(deal:Deal){ctx.deals.set(deal.id,deal);const customer=ctx.snapshot.customers.find(c=>c.id===deal.customerId);if(!customer)throw new AppError('DATA_INTEGRITY','A customer record is missing.',500);ctx.customers.set(customer.id,customer);return {deal,customer};}
  function find(id:string){const d=ctx.snapshot.deals.find(x=>x.id===id);if(!d)throw new AppError('NOT_FOUND','No matching deal was found.',404);return d;}
  function wrap<T>(name:string,fn:(input:T)=>unknown|Promise<unknown>){return async(input:T)=>{signal.throwIfAborted();const id=randomUUID();await publish({id,tool:name,status:'running',at:new Date().toISOString(),detail:'Reading approved CRM context'});try{const result=await fn(input);signal.throwIfAborted();await publish({id,tool:name,status:'succeeded',at:new Date().toISOString(),detail:name==='prepare_task'?'Draft ready; approval still required':'Source records retrieved'});return result;}catch(error){await publish({id,tool:name,status:'failed',at:new Date().toISOString(),detail:'The tool could not complete'});throw error;}};}
  return {
    get_crm_summary:tool({description:'Read exact CRM totals. These are facts, not agent judgments.',inputSchema:z.object({}).strict(),execute:wrap('get_crm_summary',()=>summaryOf(ctx.snapshot))}),
    list_deals:tool({description:'Find deals by optional account/name query and minimum MYR value. Max 20 records. Read activity context before making risk claims.',inputSchema:z.object({query:z.string().max(80).optional(),minValue:z.number().nonnegative().optional()}).strict(),execute:wrap('list_deals',(input:{query?:string;minValue?:number})=>{const q=input.query?.toLowerCase()??'';const matches=ctx.snapshot.deals.filter(d=>d.value>=(input.minValue??0)&&`${d.name} ${d.customerId}`.toLowerCase().includes(q));return {total:matches.length,deals:matches.slice(0,20).map(observe),truncated:matches.length>20};})}),
    get_deal:tool({description:'Get one exact deal and its customer using a previously discovered deal ID.',inputSchema:z.object({dealId:z.string().max(80)}).strict(),execute:wrap('get_deal',(input:{dealId:string})=>observe(find(input.dealId)))}),
    get_account_context:tool({description:'Get a deal, customer, recorded activity timeline and open follow-up tasks. Use this to investigate, compare or recommend.',inputSchema:z.object({dealId:z.string().max(80)}).strict(),execute:wrap('get_account_context',(input:{dealId:string})=>{const entity=observe(find(input.dealId));const activities=ctx.snapshot.activities.filter(a=>a.dealId===input.dealId).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,30);activities.forEach(a=>ctx.activities.set(a.id,a));ctx.detailed.add(input.dealId);return {...entity,activities:activities.map(({sessionId:_,...a})=>a),tasks:ctx.snapshot.tasks.filter(t=>t.dealId===input.dealId).map(t=>({id:t.id,title:t.title,dueDate:t.dueDate,status:t.status}))};})}),
    get_recent_activities:tool({description:'Read the most recent recorded activities for up to five deals. Activity IDs can be cited as evidence.',inputSchema:z.object({dealIds:z.array(z.string().max(80)).min(1).max(5)}).strict(),execute:wrap('get_recent_activities',(input:{dealIds:string[]})=>{input.dealIds.forEach(id=>observe(find(id)));const matches=ctx.snapshot.activities.filter(a=>input.dealIds.includes(a.dealId)).sort((a,b)=>b.at.localeCompare(a.at));const activities=matches.slice(0,60);activities.forEach(a=>{ctx.activities.set(a.id,a);ctx.detailed.add(a.dealId);});return {activities:activities.map(({sessionId:_,...a})=>a),truncated:matches.length>60};})}),
    prepare_task:tool({description:'Prepare, never execute, a follow-up task for a deal already retrieved. Only use when the user requests a task. Returns a proposal ID; the human must approve separately. This does NOT create a CRM task.',inputSchema:taskDraftSchema,execute:wrap('prepare_task',async(input:z.infer<typeof taskDraftSchema>)=>{if(!ctx.deals.has(input.dealId))throw new AppError('UNOBSERVED','Read the deal before proposing an action.');const proposal=draftProposal(sessionId,input,runId);await store.saveProposal(proposal);ctx.proposals.set(proposal.id,proposal);return publicProposal(proposal);})}),
  };
}
