"use client";
import { useState } from 'react';
import { ArrowUpRight, Search, Database, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ActionCard } from './workspace-view';
import { api } from '@/lib/browser-api';
import { money, shortDate, stages, type CrmData, type Proposal } from '@/lib/domain';
export function Explore({data,record,tab,onNavigate,onChanged}:{data:CrmData;record:string;tab:string;onNavigate:(record?:string,tab?:string)=>void;onChanged:()=>Promise<void>}){
  const [query,setQuery]=useState('');const [title,setTitle]=useState('');const [dealId,setDealId]=useState(record||data.deals[0]?.id||'');
  const [dueDate,setDueDate]=useState(()=>new Date(Date.now()+86400000).toISOString().slice(0,10));const [proposal,setProposal]=useState<Proposal|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const account=(id:string)=>data.customers.find(c=>c.id===data.deals.find(d=>d.id===id)?.customerId)?.name??id;
  const matches=(value:unknown)=>JSON.stringify(value).toLowerCase().includes(query.toLowerCase());
  const deals=data.deals.filter(d=>(!record||d.id===record)&&matches(d));
  const customers=data.customers.filter(c=>(!record||c.id===data.deals.find(d=>d.id===record)?.customerId)&&matches(c));
  const activities=data.activities.filter(a=>(!record||a.dealId===record)&&matches(a));
  const tasks=data.tasks.filter(t=>(!record||t.dealId===record)&&matches(t));
  const activeTab=['deals','customers','activities','tasks','pipeline'].includes(tab)?tab:'deals';
  async function prepare(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const result=await api<{proposal:Proposal}>('/api/proposals',{dealId,title,dueDate});setProposal(result.proposal);}catch(e){setError(e instanceof Error?e.message:'Proposal could not be prepared.');}finally{setBusy(false);}}
  return <section aria-label="Explore CRM records"><div className="section-heading"><div><p className="eyebrow"><Database size={14} aria-hidden="true"/> System of record</p><h1>Your data. Nothing hidden.</h1><p className="muted">Inspect the same records the agent uses. No model is required here.</p></div></div>
    <div className="explore-toolbar"><div className="tab-row" aria-label="Record categories">{['deals','customers','activities','tasks','pipeline'].map(item=><button key={item} aria-pressed={activeTab===item} onClick={()=>{setQuery('');onNavigate(record,item);}}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div><label className="search-field"><Search aria-hidden="true" size={16}/><span className="sr-only">Filter records</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Filter this view…"/></label></div>
    <h2 className="sr-only">{activeTab[0].toUpperCase()+activeTab.slice(1)} records</h2>
    {record&&<div className="record-filter">Showing {account(record)}<button className="text-link" onClick={()=>onNavigate('',activeTab)}>Show all records</button></div>}
    {activeTab==='deals'&&<div className="table-wrap"><table><caption>{deals.length} of {data.deals.length} deals</caption><thead><tr><th scope="col">Account / deal</th><th scope="col">Value</th><th scope="col">Stage</th><th scope="col">Target close</th><th scope="col">Details</th></tr></thead><tbody>{deals.map(deal=><tr key={deal.id}><th scope="row">{account(deal.id)}<span className="table-sub">{deal.name}</span></th><td className="number">{money(deal.value)}</td><td><span className="quiet-tag">{deal.stage}</span></td><td>{shortDate(deal.closeDate)}</td><td><button className="text-link" onClick={()=>onNavigate(deal.id,'activities')}>Activity<ArrowUpRight aria-hidden="true" size={13}/></button></td></tr>)}</tbody></table>{deals.length===0&&<p className="empty-state">No deals match this filter.</p>}</div>}
    {activeTab==='customers'&&<div className="table-wrap"><table><caption>{customers.length} of {data.customers.length} customers</caption><thead><tr><th scope="col">Customer</th><th scope="col">Domain</th><th scope="col">Industry</th><th scope="col">Owner</th></tr></thead><tbody>{customers.map(customer=><tr key={customer.id}><th scope="row">{customer.name}</th><td>{customer.domain}</td><td>{customer.industry}</td><td>{customer.owner}</td></tr>)}</tbody></table>{customers.length===0&&<p className="empty-state">No customers match this filter.</p>}</div>}
    {activeTab==='activities'&&<div className="record-list"><p className="list-count">{activities.length} of {data.activities.length} activities</p>{activities.map(activity=><article className="activity-record" key={activity.id}><div><span className="quiet-tag">{activity.kind}</span><time dateTime={activity.occurredAt}>{shortDate(activity.occurredAt)}</time></div><h3>{account(activity.dealId)}</h3><p>{activity.summary}</p><code>{activity.id}</code></article>)}{activities.length===0&&<p className="empty-state">No activities match this filter.</p>}</div>}
    {activeTab==='tasks'&&<div className="record-list"><p className="list-count">{tasks.length} of {data.tasks.length} tasks</p>{tasks.map(task=><article className="task-record" key={task.id}><div><h3>{task.title}</h3><p className="muted">{account(task.dealId)} · Due {shortDate(task.dueDate)}</p></div><span className="quiet-tag">{task.status}</span></article>)}{tasks.length===0&&<p className="empty-state">No tasks match this filter.</p>}</div>}
    {activeTab==='pipeline'&&<div className="pipeline" aria-label="Pipeline by stage">{stages.map(stage=>{const items=deals.filter(d=>d.stage===stage);return <section key={stage}><div className="pipeline-heading"><h3>{stage}</h3><span>{items.length}</span></div><p className="muted small">{money(items.reduce((sum,deal)=>sum+deal.value,0))}</p>{items.map(deal=><button className="pipeline-card" key={deal.id} onClick={()=>onNavigate(deal.id,'deals')}><strong>{account(deal.id)}</strong><span>{money(deal.value)}</span><small>Close {shortDate(deal.closeDate)}</small></button>)}</section>;})}</div>}
    <details className="manual-control"><summary><Plus size={16} aria-hidden="true"/> New follow-up without the agent</summary><p className="muted small">A manual path through the same server-side approval boundary.</p><form onSubmit={event=>void prepare(event)} className="task-form"><label>Account<select value={dealId} onChange={event=>setDealId(event.target.value)}>{data.deals.map(deal=><option value={deal.id} key={deal.id}>{account(deal.id)}</option>)}</select></label><label>Task title<input value={title} onChange={event=>setTitle(event.target.value)} required minLength={3} maxLength={120} placeholder="Clarify the remaining security questions"/></label><label>Due date<input type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)} required min={new Date().toISOString().slice(0,10)}/></label><Button type="submit" size="lg" disabled={busy}>{busy?'Preparing…':'Review task proposal'}</Button></form>{error&&<p role="alert" className="error-inline">{error}</p>}{proposal&&<ActionCard key={proposal.id} proposal={proposal} account={account(proposal.dealId)} onChanged={onChanged}/>}</details>
  </section>;
}
