'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {ArrowUpRight,Search,Plus,Table2,Columns3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {useCrm,jsonRequest} from './crm-provider';
import {ActionCard} from './action-card';
import {Timeline} from './workspace';
import {money,dateLabel,tomorrow} from '@/lib/format';
import type {PublicProposal} from '@/lib/contracts';
import {useLanguage} from './language-provider';
const tabs=['deals','customers','activities','tasks'] as const;
export function Explore(){const {data,run,busy}=useCrm(),params=useSearchParams();const {locale,t}=useLanguage();const tabValue=params.get('tab');const tab=tabs.includes(tabValue as typeof tabs[number])?tabValue as typeof tabs[number]:'deals';const selected=params.get('deal');const [search,setSearch]=useState(''),[pipeline,setPipeline]=useState(false),[manual,setManual]=useState(false);
  useEffect(()=>{setSearch('');},[tab,selected]);
  if(!data)return null;
  const snapshot=data.snapshot;const customerName=(id:string)=>snapshot.customers.find(c=>c.id===id)?.name??id;const dealName=(id:string)=>{const d=snapshot.deals.find(d=>d.id===id);return d?customerName(d.customerId):id;};
  const deal=snapshot.deals.find(d=>d.id===selected),q=search.toLowerCase();
  const deals=snapshot.deals.filter(d=>(!selected||d.id===selected)&&`${d.name} ${customerName(d.customerId)} ${d.stage}`.toLowerCase().includes(q));
  const customers=snapshot.customers.filter(c=>(!selected||c.id===deal?.customerId)&&`${c.name} ${c.industry} ${c.contact}`.toLowerCase().includes(q));
  const activities=snapshot.activities.filter(a=>(!selected||a.dealId===selected)&&`${a.text} ${dealName(a.dealId)}`.toLowerCase().includes(q)).sort((a,b)=>b.at.localeCompare(a.at));
  const tasks=snapshot.tasks.filter(task=>(!selected||task.dealId===selected)&&`${task.title} ${dealName(task.dealId)}`.toLowerCase().includes(q));
  const investigatePrompt=deal?(locale==='zh'?`调查 ${customerName(deal.customerId)} 发生了什么。`:`What happened with ${customerName(deal.customerId)}?`):'';
  return <>
    <section className="page-heading compact"><div className="eyebrow">{t('recordHeading')}</div><h1>{t('exploreTitle')}</h1><p>{t('exploreIntro')}</p></section>
    <div className="explore-toolbar"><nav aria-label={t('recordHeading')}>{tabs.map(type=><Link key={type} href={`/explore?tab=${type}${selected?`&deal=${encodeURIComponent(selected)}`:''}`} aria-current={tab===type?'page':undefined} className={tab===type?'record-tab active':'record-tab'}>{t(type)} <span>{snapshot[type].length}</span></Link>)}</nav><Button variant="outline" onClick={()=>setManual(v=>!v)}><Plus size={15}/>{manual?t('closeTaskForm'):t('newTask')}</Button></div>
    {manual?<ManualTask defaultDealId={deal?.id}/>:null}
    {selected?<div className="filter-chip">{t('accountFilter',{account:deal?customerName(deal.customerId):t('unknownRecord')})} <Link href={`/explore?tab=${tab}`}>{t('clearFilter')}</Link></div>:null}
    <section className="surface record-surface"><div className="record-controls"><label htmlFor="record-search"><Search size={16}/><Input id="record-search" aria-label={t('searchRecords')} placeholder={`${t('searchRecords')}…`} value={search} onChange={event=>setSearch(event.target.value)}/></label>{tab==='deals'?<div className="view-toggle"><Button variant={!pipeline?'secondary':'ghost'} aria-pressed={!pipeline} onClick={()=>setPipeline(false)}><Table2 size={15}/>{t('table')}</Button><Button variant={pipeline?'secondary':'ghost'} aria-pressed={pipeline} onClick={()=>setPipeline(true)}><Columns3 size={15}/>{t('pipeline')}</Button></div>:null}</div>
    {tab==='deals'&&pipeline?<div className="pipeline">{['Discovery','Qualified','Proposal','Negotiation'].map(stage=><section key={stage}><h2>{stage} <span>{deals.filter(d=>d.stage===stage).length}</span></h2>{deals.filter(d=>d.stage===stage).map(d=><Link href={`/explore?deal=${d.id}`} className="pipeline-deal" key={d.id}><strong>{customerName(d.customerId)}</strong><span>{d.name}</span><b>{money(d.value,locale)}</b></Link>)}{!deals.some(d=>d.stage===stage)?<p className="small-label">{t('noDeals')}</p>:null}</section>)}</div>:<div className="table-scroll" tabIndex={0} role="region" aria-label={`${t(tab)} ${t('table')}`}><table><caption className="sr-only">{t('recordHeading')}</caption><thead>{tab==='deals'?<tr><th>{t('accountDeal')}</th><th>{t('value')}</th><th>{t('stage')}</th><th>{t('owner')}</th><th>{t('targetClose')}</th><th>{t('inspect')}</th></tr>:tab==='customers'?<tr><th>{t('customer')}</th><th>{t('industry')}</th><th>{t('contact')}</th><th>{t('sampleEmail')}</th></tr>:tab==='activities'?<tr><th>{t('when')}</th><th>{t('account')}</th><th>{t('type')}</th><th>{t('recordedSource')}</th></tr>:<tr><th>{t('tasks')}</th><th>{t('account')}</th><th>{t('dueDate')}</th><th>{t('status')}</th><th>{t('created')}</th></tr>}</thead><tbody>
      {tab==='deals'?deals.map(d=><tr key={d.id}><td><strong>{customerName(d.customerId)}</strong><span className="cell-sub">{d.name}</span></td><td>{money(d.value,locale)}</td><td><span className="stage-tag">{d.stage}</span></td><td>{d.owner}</td><td>{dateLabel(d.closeDate,locale)}</td><td><Link href={`/explore?deal=${d.id}`} aria-label={`${t('openRecord')} ${customerName(d.customerId)}`}>{t('open')} <ArrowUpRight size={13}/></Link></td></tr>):null}
      {tab==='customers'?customers.map(customer=><tr key={customer.id}><td><strong>{customer.name}</strong></td><td>{customer.industry}</td><td>{customer.contact}</td><td>{customer.email}</td></tr>):null}
      {tab==='activities'?activities.map(activity=><tr key={activity.id} id={activity.id}><td>{dateLabel(activity.at,locale)}</td><td>{dealName(activity.dealId)}</td><td>{activity.kind}</td><td className="source-cell">{activity.text}<span className="cell-sub">{activity.id}</span></td></tr>):null}
      {tab==='tasks'?tasks.map(task=><tr key={task.id}><td><strong>{task.title}</strong><span className="cell-sub">{task.note}</span></td><td>{dealName(task.dealId)}</td><td>{dateLabel(task.dueDate,locale)}</td><td><span className="stage-tag">{task.status}</span></td><td>{dateLabel(task.createdAt,locale)}</td></tr>):null}
    </tbody></table>{(tab==='deals'?deals.length:tab==='customers'?customers.length:tab==='activities'?activities.length:tasks.length)===0?<div className="empty-inline"><p>{search?t('noSearch'):tab==='tasks'?t('noTasks'):t('noRecords')}</p><span>{tab==='tasks'?t('prepareHint'):t('filterHint')}</span></div>:null}</div>}
    <div className="table-footer">{t('sourceFooter',{database:data.database==='postgres'?'PostgreSQL':t('localDemo'),date:dateLabel(data.datasetAsOf,locale)})}</div></section>
    {deal?<section className="record-detail surface"><div className="section-heading"><div><span className="eyebrow">{t('fullRecord')}</span><h2>{customerName(deal.customerId)} · {deal.name}</h2><p className="small-label">{t('recordId',{id:deal.id})}</p></div><Button variant="outline" disabled={busy} onClick={()=>void run(investigatePrompt,[deal.id])}>{t('investigateAgent')} <ArrowUpRight size={15}/></Button></div><Timeline activities={snapshot.activities.filter(activity=>activity.dealId===deal.id).sort((a,b)=>a.at.localeCompare(b.at))}/></section>:null}
  </>;
}
function ManualTask({defaultDealId}:{defaultDealId?:string}){const {data}=useCrm();const {t}=useLanguage();const [proposal,setProposal]=useState<PublicProposal|null>(null),[pending,setPending]=useState(false),[error,setError]=useState<string|null>(null);if(!data)return null;
  return <section className="manual-task surface"><h2>{t('prepareInternal')}</h2><p>{t('reviewProposal')}</p><form className="manual-form" onSubmit={async event=>{event.preventDefault();if(pending)return;const form=new FormData(event.currentTarget);setPending(true);setError(null);try{const result=await jsonRequest<{proposal:PublicProposal}>('/api/actions',{intent:'prepare',draft:{dealId:form.get('dealId'),title:form.get('title'),note:form.get('note'),dueDate:form.get('dueDate')}});setProposal(result.proposal);}catch(error){setError(error instanceof Error?error.message:'Unable to prepare task.');}finally{setPending(false);}}}>
    <label>{t('account')}<select name="dealId" defaultValue={defaultDealId??data.snapshot.deals[0]?.id} required>{data.snapshot.deals.map(deal=><option key={deal.id} value={deal.id}>{data.snapshot.customers.find(customer=>customer.id===deal.customerId)?.name} — {deal.name}</option>)}</select></label><label>{t('taskTitle')}<Input name="title" minLength={3} maxLength={140} required placeholder={t('nextStep')}/></label><label>{t('dueDate')}<Input name="dueDate" type="date" defaultValue={tomorrow()} required/></label><label className="wide">{t('taskContext')}<textarea name="note" maxLength={800} rows={2} placeholder={t('followUpContext')}/></label><Button type="submit" disabled={pending}>{pending?t('preparing'):t('reviewTask')}</Button>
  </form>{error?<p role="alert" className="inline-error">{error}</p>:null}{proposal?<ActionCard proposal={proposal} onChange={setProposal}/>:null}</section>;
}
