'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {ArrowUpRight,Search,Plus,Table2,Columns3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {useCrm,jsonRequest} from './crm-provider';
import {ActionCard} from './action-card';
import {Timeline} from './workspace';
import {money,dateLabel,tomorrow} from '@/lib/format';
import type {PublicProposal} from '@/lib/contracts';
const tabs=['deals','customers','activities','tasks'] as const;
export function Explore(){const {data,run,busy}=useCrm(),params=useSearchParams();const tabValue=params.get('tab');const tab=tabs.includes(tabValue as typeof tabs[number])?tabValue as typeof tabs[number]:'deals';const selected=params.get('deal');const [search,setSearch]=useState(''),[pipeline,setPipeline]=useState(false),[manual,setManual]=useState(false);
  useEffect(()=>{setSearch('');},[tab,selected]);
  if(!data)return null;
  const snapshot=data.snapshot;const customerName=(id:string)=>snapshot.customers.find(c=>c.id===id)?.name??id;const dealName=(id:string)=>{const d=snapshot.deals.find(d=>d.id===id);return d?customerName(d.customerId):id;};
  const deal=snapshot.deals.find(d=>d.id===selected),q=search.toLowerCase();
  const deals=snapshot.deals.filter(d=>(!selected||d.id===selected)&&`${d.name} ${customerName(d.customerId)} ${d.stage}`.toLowerCase().includes(q));
  const customers=snapshot.customers.filter(c=>(!selected||c.id===deal?.customerId)&&`${c.name} ${c.industry} ${c.contact}`.toLowerCase().includes(q));
  const activities=snapshot.activities.filter(a=>(!selected||a.dealId===selected)&&`${a.text} ${dealName(a.dealId)}`.toLowerCase().includes(q)).sort((a,b)=>b.at.localeCompare(a.at));
  const tasks=snapshot.tasks.filter(t=>(!selected||t.dealId===selected)&&`${t.title} ${dealName(t.dealId)}`.toLowerCase().includes(q));
  return <>
    <section className="page-heading compact"><div className="eyebrow">SYSTEM OF RECORD</div><h1>Your data. In full view.</h1><p>Inspect the source, follow the history, or create a task manually. No model is needed here.</p></section>
    <div className="explore-toolbar"><nav aria-label="CRM record types">{tabs.map(t=><Link key={t} href={`/explore?tab=${t}${selected?`&deal=${encodeURIComponent(selected)}`:''}`} aria-current={tab===t?'page':undefined} className={tab===t?'record-tab active':'record-tab'}>{t.charAt(0).toUpperCase()+t.slice(1)} <span>{snapshot[t].length}</span></Link>)}</nav><Button variant="outline" onClick={()=>setManual(v=>!v)}><Plus size={15}/>{manual?'Close task form':'New task'}</Button></div>
    {manual?<ManualTask defaultDealId={deal?.id}/>:null}
    {selected?<div className="filter-chip">Account filter: {deal?customerName(deal.customerId):'Unknown record'} <Link href={`/explore?tab=${tab}`}>Clear filter</Link></div>:null}
    <section className="surface record-surface"><div className="record-controls"><label htmlFor="record-search"><Search size={16}/><Input id="record-search" aria-label="Search records" placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{tab==='deals'?<div className="view-toggle"><Button variant={!pipeline?'secondary':'ghost'} aria-pressed={!pipeline} onClick={()=>setPipeline(false)}><Table2 size={15}/> Table</Button><Button variant={pipeline?'secondary':'ghost'} aria-pressed={pipeline} onClick={()=>setPipeline(true)}><Columns3 size={15}/> Pipeline</Button></div>:null}</div>
    {tab==='deals'&&pipeline?<div className="pipeline">{['Discovery','Qualified','Proposal','Negotiation'].map(stage=><section key={stage}><h2>{stage} <span>{deals.filter(d=>d.stage===stage).length}</span></h2>{deals.filter(d=>d.stage===stage).map(d=><Link href={`/explore?deal=${d.id}`} className="pipeline-deal" key={d.id}><strong>{customerName(d.customerId)}</strong><span>{d.name}</span><b>{money(d.value)}</b></Link>)}{!deals.some(d=>d.stage===stage)?<p className="small-label">No deals</p>:null}</section>)}</div>:<div className="table-scroll" tabIndex={0} role="region" aria-label={`${tab} data table`}><table><caption className="sr-only">{tab} from the CRM database</caption><thead>{tab==='deals'?<tr><th>Account / Deal</th><th>Value</th><th>Stage</th><th>Owner</th><th>Target close</th><th>Inspect</th></tr>:tab==='customers'?<tr><th>Customer</th><th>Industry</th><th>Contact</th><th>Sample email</th></tr>:tab==='activities'?<tr><th>When</th><th>Account</th><th>Type</th><th>Recorded source</th></tr>:<tr><th>Task</th><th>Account</th><th>Due date</th><th>Status</th><th>Created</th></tr>}</thead><tbody>
      {tab==='deals'?deals.map(d=><tr key={d.id}><td><strong>{customerName(d.customerId)}</strong><span className="cell-sub">{d.name}</span></td><td>{money(d.value)}</td><td><span className="stage-tag">{d.stage}</span></td><td>{d.owner}</td><td>{dateLabel(d.closeDate)}</td><td><Link href={`/explore?deal=${d.id}`} aria-label={`Open ${customerName(d.customerId)} record`}>Open <ArrowUpRight size={13}/></Link></td></tr>):null}
      {tab==='customers'?customers.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.industry}</td><td>{c.contact}</td><td>{c.email}</td></tr>):null}
      {tab==='activities'?activities.map(a=><tr key={a.id} id={a.id}><td>{dateLabel(a.at)}</td><td>{dealName(a.dealId)}</td><td>{a.kind}</td><td className="source-cell">{a.text}<span className="cell-sub">{a.id}</span></td></tr>):null}
      {tab==='tasks'?tasks.map(t=><tr key={t.id}><td><strong>{t.title}</strong><span className="cell-sub">{t.note}</span></td><td>{dealName(t.dealId)}</td><td>{dateLabel(t.dueDate)}</td><td><span className="stage-tag">{t.status}</span></td><td>{dateLabel(t.createdAt)}</td></tr>):null}
    </tbody></table>{(tab==='deals'?deals.length:tab==='customers'?customers.length:tab==='activities'?activities.length:tasks.length)===0?<div className="empty-inline"><p>{search?'No records match your search.':tab==='tasks'?'No follow-up tasks yet.':'No records available.'}</p><span>{tab==='tasks'?'Approve a proposed task, or use New task to prepare one manually.':'Try another filter. The source data has not been altered.'}</span></div>:null}</div>}
    <div className="table-footer">Source: {data.database==='postgres'?'PostgreSQL':'Local file-backed demo'} · Fictional data as of {dateLabel(data.datasetAsOf)} · Tasks are scoped to this browser session</div></section>
    {deal?<section className="record-detail surface"><div className="section-heading"><div><span className="eyebrow">FULL RECORD</span><h2>{customerName(deal.customerId)} · {deal.name}</h2><p className="small-label">Record ID: {deal.id}</p></div><Button variant="outline" disabled={busy} onClick={()=>void run(`What happened with ${customerName(deal.customerId)}?`,[deal.id])}>Investigate with agent <ArrowUpRight size={15}/></Button></div><Timeline activities={snapshot.activities.filter(a=>a.dealId===deal.id).sort((a,b)=>a.at.localeCompare(b.at))}/></section>:null}
  </>;
}
function ManualTask({defaultDealId}:{defaultDealId?:string}){const {data}=useCrm();const [proposal,setProposal]=useState<PublicProposal|null>(null),[pending,setPending]=useState(false),[error,setError]=useState<string|null>(null);if(!data)return null;
  return <section className="manual-task surface"><h2>Prepare an internal follow-up</h2><p>You will review the saved proposal before a task is created.</p><form className="manual-form" onSubmit={async e=>{e.preventDefault();if(pending)return;const form=new FormData(e.currentTarget);setPending(true);setError(null);try{const result=await jsonRequest<{proposal:PublicProposal}>('/api/actions',{intent:'prepare',draft:{dealId:form.get('dealId'),title:form.get('title'),note:form.get('note'),dueDate:form.get('dueDate')}});setProposal(result.proposal);}catch(e){setError(e instanceof Error?e.message:'Unable to prepare task.');}finally{setPending(false);}}}>
    <label>Account<select name="dealId" defaultValue={defaultDealId??data.snapshot.deals[0]?.id} required>{data.snapshot.deals.map(d=><option key={d.id} value={d.id}>{data.snapshot.customers.find(c=>c.id===d.customerId)?.name} — {d.name}</option>)}</select></label><label>Task title<Input name="title" minLength={3} maxLength={140} required placeholder="Clarify the next step"/></label><label>Due date<Input name="dueDate" type="date" defaultValue={tomorrow()} required/></label><label className="wide">Context<textarea name="note" maxLength={800} rows={2} placeholder="What should the account owner follow up on?"/></label><Button type="submit" disabled={pending}>{pending?'Preparing…':'Review task proposal'}</Button>
  </form>{error?<p role="alert" className="inline-error">{error}</p>:null}{proposal?<ActionCard proposal={proposal} onChange={setProposal}/>:null}</section>;
}
