'use client';
import {createContext,useCallback,useContext,useEffect,useMemo,useState} from 'react';
import {Languages} from 'lucide-react';
import {Button} from '@/components/ui/button';

export type Locale='en'|'zh';
type Variables=Record<string,string|number>;
const messages:Record<Locale,Record<string,string>>={
  en:{
    languageLabel:'Language',english:'English',chinese:'中文',
    skipToContent:'Skip to main content',homeAria:'Agent-native CRM home',today:'Today',workspace:'Workspace',explore:'Explore',liveModel:'Live model',scriptedDemo:'Scripted demo',contextToday:'TODAY',contextWorkspace:'INTENT TO ACTION',contextExplore:'YOUR SOURCE OF RECORD',prototype:'Prototype · Fictional CRM data',dataUnavailable:'CRM data is unavailable.',retryData:'Retry data',loadingSource:'Loading the source of record…',footerTagline:'Less administration. More informed decisions.',footerLink:'Your data is always accessible',
    loginTitle:'Welcome back.',loginIntro:'Enter the workspace password to access this private CRM prototype.',workspacePassword:'Workspace password',loginHelp:'This password is configured only for this workspace.',signIn:'Sign in',signingIn:'Signing in…',loginSecurity:'Your password is never stored in the browser.',loginFailed:'We could not sign you in. Please try again.',loginReach:'We could not reach the workspace. Please try again.',
    askCrm:'Ask CRM',chatTitle:'CRM assistant',chatLive:'Live model · recent context on',chatDemo:'Scripted demo · recent context on',newConversation:'Start a new conversation',minimizeChat:'Minimize CRM chat',keepThread:'Keep the thread going.',chatEmpty:'I remember the recent discussion while this panel stays open, then re-check CRM records before making a recommendation.',you:'You',checkingRecords:'Checking the source records…',chatInput:'Ask a follow-up or start a new CRM question…',chatInputLabel:'What would you like to move forward?',chatLiveHelp:'Recent chat context · Source-backed facts',chatDemoHelp:'Scripted demo · Recent chat context',stopRun:'Stop run',stop:'Stop',runRequest:'Run request',send:'Send',chatFailed:'I could not complete that request. The workspace shows the error and keeps your earlier context available.',pendingTask:'Pending task proposal (not created)',taskDue:'Due',taskDetails:'Details',mainNavigation:'Main navigation',
    todayEyebrow:'A CLEARER START',todayTitle:'Start with what matters.',todayIntro:'Your CRM holds the details. Your workspace brings the next step into focus.',activeDeals:'Active deals',pipelineValue:'Pipeline value',customers:'Customers',followUpTasks:'Your follow-up tasks',exploreRecords:'Explore all records',latestFocus:'Your latest focus',savedAnalysis:'Saved analysis from {date} · {mode} · Not a live prediction',openSaved:'Open saved workspace',inspectSource:'Inspect source record',needsAttention:'What needs your attention?',startingPoint:'Choose a starting point, or describe your own intent below.',readApprove:'Read first. Act with approval.',prioritize:'01 / PRIORITIZE',focusCard:'Find the conversations worth moving forward.',focusCardCopy:'Review account signals and turn a busy pipeline into a short, evidence-backed focus list.',reviewPriorities:'Review today’s priorities',readOnly:'Reads CRM data · Does not change records',understand:'02 / UNDERSTAND',understandCard:'Look behind an account signal.',understandCopy:'Investigate ACME’s open questions, recent activity, and the context behind the proposal.',investigateAcme:'Investigate ACME',compare:'03 / COMPARE',compareCard:'See the differences side by side.',compareCopy:'Compare ACME and Nova using the same source records, not a generated set of numbers.',compareAccounts:'Compare accounts',recentWorkspaces:'Recent workspaces',browserSession:'This browser session',noAnalysis:'No analysis has run yet.',firstRequest:'Your first request will leave a saved workspace and an inspectable tool trail here.',smallerInterface:'A smaller interface. Not a smaller view.',dataNote:'All {deals} deals remain available in Explore. Agent suggestions never replace your source of record.',openData:'Open the data',sampleData:'Sample dataset as of {date}.',
    adaptiveWorkspace:'ADAPTIVE WORKSPACE',workspaceFallback:'Your intent, a working view.',workspaceIntro:'Ask a question below, or start with today’s priorities. The interface follows the task.',latestFailed:'The latest request was not completed.',continueExplore:'Continue in Explore',dismiss:'Dismiss',loadingWorkspace:'Loading saved workspace…',startingLoop:'Starting the tool loop…',verifiedOnly:'Only completed tool events and verified source results are shown.',toolActivity:'Tool activity · {count} completed calls',inspectExecution:'Inspect execution',dealsRetrieved:'deals retrieved',activityContext:'with activity context',view:'{type} view',viewRecords:'View all records',checked:'Checked {date}',scriptedInterpretation:'Scripted interpretation, not a live LLM',liveInterpretation:'Live model interpretation',noMatching:'No matching analysis to display.',nothingHidden:'Nothing is being hidden or replaced. Try a supported request or inspect the full dataset.',openExplore:'Open Explore',startQuestion:'Start with a business question.',startQuestionCopy:'A focus list, an account investigation, or a comparison—not another chat transcript.',needsAttentionSignal:'Needs attention',opportunity:'Opportunity',closerLook:'Worth a closer look',recordedContext:'Recorded context',interpretation:'Interpretation · based on the records below',investigateAccount:'Investigate {account}',record:'Record',noEvidence:'No source evidence was returned for this record.',noActivity:'No recorded activity.',followUpTask:'Follow-up task',customerMeeting:'Customer meeting',emailRecorded:'Email recorded',accountNote:'Account note',target:'Target {date}',openRecord:'Open record',recordsShow:'What the records show',timeline:'Timeline',possibleNext:'Possible next step',tentative:'This is an interpretation—not a confirmed customer decision.',prepareFollowUp:'Prepare follow-up task',supportingEvidence:'Supporting evidence',accountComparison:'Account comparison',sourceFacts:'Source facts',dealValue:'Deal value',stage:'Stage',targetClose:'Target close',accountOwner:'Account owner',evidence:'Evidence',inspect:'Inspect',
    recordHeading:'SYSTEM OF RECORD',exploreTitle:'Your data. In full view.',exploreIntro:'Inspect the source, follow the history, or create a task manually. No model is needed here.',deals:'Deals',activities:'Activities',tasks:'Tasks',newTask:'New task',closeTaskForm:'Close task form',accountFilter:'Account filter: {account}',unknownRecord:'Unknown record',clearFilter:'Clear filter',searchRecords:'Search records',table:'Table',pipeline:'Pipeline',noDeals:'No deals',noRecords:'No records available.',noSearch:'No records match your search.',noTasks:'No follow-up tasks yet.',prepareHint:'Approve a proposed task, or use New task to prepare one manually.',filterHint:'Try another filter. The source data has not been altered.',sourceFooter:'Source: {database} · Fictional data as of {date} · Tasks are scoped to this browser session',localDemo:'Local file-backed demo',fullRecord:'FULL RECORD',recordId:'Record ID: {id}',investigateAgent:'Investigate with agent',prepareInternal:'Prepare an internal follow-up',reviewProposal:'You will review the saved proposal before a task is created.',account:'Account',taskTitle:'Task title',dueDate:'Due date',taskContext:'Context',nextStep:'Clarify the next step',followUpContext:'What should the account owner follow up on?',preparing:'Preparing…',reviewTask:'Review task proposal',accountDeal:'Account / Deal',value:'Value',owner:'Owner',customer:'Customer',industry:'Industry',contact:'Contact',sampleEmail:'Sample email',when:'When',type:'Type',recordedSource:'Recorded source',status:'Status',created:'Created',open:'Open',
    approvalRequired:'YOUR APPROVAL REQUIRED',approvedSaved:'APPROVED AND SAVED',rejected:'REJECTED',proposedTask:'Proposed follow-up task',due:'Due {date}',approvalCopy:'Creates one internal task. No email is sent. Proposal expires after 30 minutes.',processing:'Processing…',approveCreate:'Approve & create task',reject:'Reject',taskStored:'Task created and stored.',viewExplore:'View in Explore',proposalRejected:'Proposal rejected. No task was created.',actionFailed:'The action failed.',runIncomplete:'This saved run did not finish. Start a new request; the previous run is not treated as complete.',savedUnavailable:'Saved workspace unavailable.',agentUnavailable:'Unable to start the agent.',noResponse:'No response stream was received.',connectionEnded:'The connection ended before a complete workspace arrived. Retry or use Explore.',runStopped:'Run stopped. No unapproved CRM change was made.',runFailed:'The run failed. Your previous workspace is still available.',
  },
  zh:{
    languageLabel:'语言',english:'English',chinese:'中文',
    skipToContent:'跳至主要内容',homeAria:'Agent-native CRM 首页',today:'今日',workspace:'工作区',explore:'浏览',liveModel:'真实模型',scriptedDemo:'脚本演示',contextToday:'今日',contextWorkspace:'从意图到行动',contextExplore:'你的数据记录',prototype:'原型 · 虚构 CRM 数据',dataUnavailable:'CRM 数据暂时不可用。',retryData:'重试加载',loadingSource:'正在加载数据记录…',footerTagline:'少做管理，多做明智决策。',footerLink:'你的数据随时可查',
    loginTitle:'欢迎回来。',loginIntro:'输入工作区密码以进入此私有 CRM 原型。',workspacePassword:'工作区密码',loginHelp:'此密码仅为当前工作区配置。',signIn:'登录',signingIn:'正在登录…',loginSecurity:'密码不会存储在浏览器中。',loginFailed:'无法登录，请重试。',loginReach:'无法连接工作区，请重试。',
    askCrm:'询问 CRM',chatTitle:'CRM 助手',chatLive:'真实模型 · 已启用近期上下文',chatDemo:'脚本演示 · 已启用近期上下文',newConversation:'开始新对话',minimizeChat:'最小化 CRM 对话',keepThread:'继续这段对话。',chatEmpty:'面板开启期间会保留近期讨论；在给出建议前，助手仍会重新核对 CRM 记录。',you:'你',checkingRecords:'正在核对源记录…',chatInput:'继续追问，或开始新的 CRM 问题…',chatInputLabel:'你想推进什么？',chatLiveHelp:'近期对话上下文 · 有来源支持的事实',chatDemoHelp:'脚本演示 · 近期对话上下文',stopRun:'停止请求',stop:'停止',runRequest:'发送请求',send:'发送',chatFailed:'未能完成这个请求。工作区会显示错误，且会保留你之前的上下文。',pendingTask:'待审批任务提案（尚未创建）',taskDue:'到期日',taskDetails:'详情',mainNavigation:'主导航',
    todayEyebrow:'更清晰的开始',todayTitle:'从重要的事开始。',todayIntro:'CRM 保存细节，工作区让下一步更清晰。',activeDeals:'进行中的商机',pipelineValue:'管道金额',customers:'客户',followUpTasks:'你的跟进任务',exploreRecords:'查看所有记录',latestFocus:'你最近的重点',savedAnalysis:'保存于 {date} · {mode} · 并非实时预测',openSaved:'打开已保存工作区',inspectSource:'查看源记录',needsAttention:'什么需要你的关注？',startingPoint:'选择一个起点，或在下方描述你的意图。',readApprove:'先读后做，操作需审批。',prioritize:'01 / 优先处理',focusCard:'找出值得继续推进的对话。',focusCardCopy:'审查客户信号，把繁忙管道变成简短且有证据支持的重点清单。',reviewPriorities:'查看今日优先事项',readOnly:'读取 CRM 数据 · 不会修改记录',understand:'02 / 了解情况',understandCard:'深入了解客户信号。',understandCopy:'查看 ACME 未解决的问题、近期活动及提案背景。',investigateAcme:'调查 ACME',compare:'03 / 对比',compareCard:'并排查看差异。',compareCopy:'用同一组源记录对比 ACME 与 Nova，而非使用生成的数字。',compareAccounts:'对比客户',recentWorkspaces:'最近工作区',browserSession:'此浏览器会话',noAnalysis:'尚未运行任何分析。',firstRequest:'你的第一次请求会在这里留下已保存工作区和可查看的工具记录。',smallerInterface:'界面更小，视野不变。',dataNote:'全部 {deals} 个商机仍可在浏览中查看。助手建议不会替代你的源数据记录。',openData:'打开数据',sampleData:'示例数据截至 {date}。',
    adaptiveWorkspace:'自适应工作区',workspaceFallback:'你的意图，一种工作视图。',workspaceIntro:'在下方提问，或从今日优先事项开始。界面会随任务调整。',latestFailed:'最新请求未能完成。',continueExplore:'继续在浏览中查看',dismiss:'关闭',loadingWorkspace:'正在加载已保存工作区…',startingLoop:'正在启动工具流程…',verifiedOnly:'仅显示已完成的工具事件和已验证的源结果。',toolActivity:'工具活动 · 已完成 {count} 次调用',inspectExecution:'查看执行过程',dealsRetrieved:'已获取商机',activityContext:'具有活动背景',view:'{type} 视图',viewRecords:'查看所有记录',checked:'核对于 {date}',scriptedInterpretation:'脚本解释，并非真实 LLM',liveInterpretation:'真实模型解释',noMatching:'没有可显示的匹配分析。',nothingHidden:'没有隐藏或替换任何内容。请尝试支持的请求，或查看完整数据集。',openExplore:'打开浏览',startQuestion:'从一个业务问题开始。',startQuestionCopy:'重点清单、客户调查或对比，而不是另一份聊天记录。',needsAttentionSignal:'需要关注',opportunity:'机会',closerLook:'值得深入查看',recordedContext:'已记录背景',interpretation:'解读 · 基于下方记录',investigateAccount:'调查 {account}',record:'记录',noEvidence:'此记录没有返回源证据。',noActivity:'没有已记录活动。',followUpTask:'跟进任务',customerMeeting:'客户会议',emailRecorded:'已记录邮件',accountNote:'客户备注',target:'目标日期 {date}',openRecord:'打开记录',recordsShow:'记录显示的内容',timeline:'时间线',possibleNext:'可考虑的下一步',tentative:'这是一项解读，并非已确认的客户决定。',prepareFollowUp:'准备跟进任务',supportingEvidence:'支持证据',accountComparison:'客户对比',sourceFacts:'源事实',dealValue:'商机金额',stage:'阶段',targetClose:'目标成交日期',accountOwner:'客户负责人',evidence:'证据',inspect:'查看',
    recordHeading:'数据记录',exploreTitle:'完整查看你的数据。',exploreIntro:'检查源数据、查看历史，或手动创建任务；此处不需要模型。',deals:'商机',activities:'活动',tasks:'任务',newTask:'新建任务',closeTaskForm:'关闭任务表单',accountFilter:'客户筛选：{account}',unknownRecord:'未知记录',clearFilter:'清除筛选',searchRecords:'搜索记录',table:'表格',pipeline:'管道',noDeals:'没有商机',noRecords:'没有可用记录。',noSearch:'没有记录符合搜索条件。',noTasks:'暂无跟进任务。',prepareHint:'审批一个待处理提案，或使用“新建任务”手动准备。',filterHint:'尝试其他筛选条件，源数据未被修改。',sourceFooter:'来源：{database} · 虚构数据截至 {date} · 任务仅限此浏览器会话',localDemo:'本地文件演示',fullRecord:'完整记录',recordId:'记录 ID：{id}',investigateAgent:'使用助手调查',prepareInternal:'准备内部跟进',reviewProposal:'在创建任务前，你会先检查已保存的提案。',account:'客户',taskTitle:'任务标题',dueDate:'到期日',taskContext:'背景',nextStep:'明确下一步',followUpContext:'客户负责人应跟进什么？',preparing:'正在准备…',reviewTask:'检查任务提案',accountDeal:'客户 / 商机',value:'金额',owner:'负责人',customer:'客户',industry:'行业',contact:'联系人',sampleEmail:'示例邮箱',when:'时间',type:'类型',recordedSource:'已记录来源',status:'状态',created:'创建时间',open:'打开',
    approvalRequired:'需要你的审批',approvedSaved:'已审批并保存',rejected:'已拒绝',proposedTask:'建议的跟进任务',due:'到期 {date}',approvalCopy:'会创建一项内部任务，不会发送邮件。提案将在 30 分钟后过期。',processing:'正在处理…',approveCreate:'审批并创建任务',reject:'拒绝',taskStored:'任务已创建并保存。',viewExplore:'在浏览中查看',proposalRejected:'提案已拒绝，未创建任务。',actionFailed:'操作未能完成。',runIncomplete:'此已保存请求未完成。请重新发起请求；先前请求不会被视为完成。',savedUnavailable:'已保存的工作区不可用。',agentUnavailable:'无法启动助手。',noResponse:'未收到响应流。',connectionEnded:'在收到完整工作区前连接已结束。请重试或使用浏览。',runStopped:'请求已停止，未进行任何未经批准的 CRM 修改。',runFailed:'请求失败，之前的工作区仍可使用。'
  }
};
function interpolate(text:string,values?:Variables){return text.replace(/\{(\w+)\}/g,(_,key)=>String(values?.[key]??`{${key}}`));}
type LanguageValue={locale:Locale;setLocale:(locale:Locale)=>void;t:(key:string,values?:Variables)=>string};
const LanguageContext=createContext<LanguageValue|null>(null);
export function LanguageProvider({children}:{children:React.ReactNode}){
  const [locale,setLocaleState]=useState<Locale>('en');
  useEffect(()=>{const saved=window.localStorage.getItem('crm-locale');if(saved==='en'||saved==='zh')setLocaleState(saved);},[]);
  useEffect(()=>{window.localStorage.setItem('crm-locale',locale);document.documentElement.lang=locale==='zh'?'zh-CN':'en';},[locale]);
  const setLocale=useCallback((next:Locale)=>setLocaleState(next),[]);
  const t=useCallback((key:string,values?:Variables)=>interpolate(messages[locale][key]??messages.en[key]??key,values),[locale]);
  const value=useMemo(()=>({locale,setLocale,t}),[locale,setLocale,t]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage(){const context=useContext(LanguageContext);if(!context)throw new Error('Language provider is required');return context;}
export function LanguageToggle(){const {locale,setLocale,t}=useLanguage();return <div className="language-toggle" role="group" aria-label={t('languageLabel')}><Languages size={15} aria-hidden="true"/><Button type="button" size="xs" variant={locale==='en'?'secondary':'ghost'} aria-pressed={locale==='en'} onClick={()=>setLocale('en')}>{t('english')}</Button><Button type="button" size="xs" variant={locale==='zh'?'secondary':'ghost'} aria-pressed={locale==='zh'} onClick={()=>setLocale('zh')}>{t('chinese')}</Button></div>;}
