'use client';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,AlertTriangle,TrendingUp,Minus,CheckCircle2,LoaderCircle,FileText,Clock3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {useCrm} from './crm-provider';
import {ActionCard} from './action-card';
import {Prose} from './prose';
import {money,dateLabel} from '@/lib/format';
import type {Activity,WorkspaceItem} from '@/lib/contracts';
import {useLanguage} from './language-provider';

export function EvidenceList({activities}:{activities:Activity[]}){const {locale,t}=useLanguage();return <div className="evidence-list">{activities.length?activities.map(a=><div className="evidence-item" key={a.id}><FileText size={16}/><div><p>{a.text}</p><Link href={`/explore?tab=activities&deal=${encodeURIComponent(a.dealId)}#${a.id}`}>{dateLabel(a.at,locale)} · {a.kind} · {t('sourceFacts')} <ArrowUpRight size={12}/></Link></div></div>):<p className="small-label">{t('noEvidence')}</p>}</div>;}
export function Timeline({activities}:{activities:Activity[]}){const {locale,t}=useLanguage();const labels:Record<Activity['kind'],string>={task:t('followUpTask'),meeting:t('customerMeeting'),email:t('emailRecorded'),note:t('accountNote')};return <ol className="timeline">{activities.length?activities.map(a=><li key={a.id}><span className="timeline-dot"/><div><time dateTime={a.at}>{dateLabel(a.at,locale)}</time><strong>{labels[a.kind]}</strong><p>{a.text}</p></div></li>):<li>{t('noActivity')}</li>}</ol>;}
function Signal({item}:{item:WorkspaceItem}){const {t}=useLanguage();const Icon=item.signal==='attention'?AlertTriangle:item.signal==='opportunity'?TrendingUp:Minus;const labels:Record<WorkspaceItem['signal'],string>={attention:t('needsAttentionSignal'),opportunity:t('opportunity'),watch:t('closerLook'),neutral:t('recordedContext')};return <span className={`signal ${item.signal}`}><Icon size={14}/>{labels[item.signal]}</span>;}
function SituationCard({item}:{item:WorkspaceItem}){const {run,busy}=useCrm();const {locale,t}=useLanguage();const prompt=locale==='zh'?`ACME 发生了什么？`.replace('ACME',item.customer.name):`What happened with ${item.customer.name}?`;return <article className="situation-card"><div className="situation-top"><span className="account-monogram">{item.customer.name.slice(0,1)}</span><Signal item={item}/></div><h3>{item.customer.name}</h3><p className="deal-caption">{item.deal.name}</p><div className="deal-meta"><strong>{money(item.deal.value,locale)}</strong><span>{item.deal.stage}</span></div><div className="interpretation"><span className="small-label">{t('interpretation')}</span><Prose>{item.interpretation}</Prose></div><EvidenceList activities={item.evidence.slice(0,2)}/><div className="card-actions"><Button variant="outline" disabled={busy} onClick={()=>void run(prompt,[item.deal.id])}>{t('investigateAccount',{account:item.customer.name})} <ArrowRight size={15}/></Button><Link href={`/explore?deal=${item.deal.id}`}>{t('record')} <ArrowUpRight size={14}/></Link></div></article>;}
export function WorkspacePage(){const {workspace,busy,runLoading,events,error,notice,run,clearError}=useCrm();const {locale,t}=useLanguage();const latest=events.at(-1);const focusPrompt=locale==='zh'?'我今天应该优先处理什么？':'What should I focus on today?';
  return <>
    <section className="page-heading compact"><div className="eyebrow">{t('adaptiveWorkspace')}</div><h1>{workspace?.title??t('workspaceFallback')}</h1>{workspace?<Prose>{workspace.summary}</Prose>:<p>{t('workspaceIntro')}</p>}</section>
    {error?<div className="notice error" role="alert"><div><strong>{t('latestFailed')}</strong><p>{error}</p><Link href="/explore">{t('continueExplore')}</Link></div><Button variant="ghost" onClick={clearError}>{t('dismiss')}</Button></div>:null}
    {notice?<p className="run-notice" role="status">{notice}</p>:null}
    {busy||runLoading?<div className="run-progress" role="status" aria-live="polite"><LoaderCircle className="spin" size={19}/><div><strong>{runLoading?t('loadingWorkspace'):latest?`${latest.tool.replaceAll('_',' ')} · ${latest.status}`:t('startingLoop')}</strong><span>{t('verifiedOnly')}</span></div></div>:null}
    {events.length?<details className="tool-trail"><summary><Clock3 size={15}/> {t('toolActivity',{count:events.filter(e=>e.status==='succeeded').length})} <span>{t('inspectExecution')}</span></summary><div>{events.map((event,index)=><div className="tool-row" key={`${event.id}-${index}`}><span className={`tool-state ${event.status}`}>{event.status==='succeeded'?<CheckCircle2 size={15}/>:event.status==='running'?<LoaderCircle size={15}/>:<AlertTriangle size={15}/>}</span><code>{event.tool}</code><span>{event.status}</span><span>{event.detail}</span></div>)}</div></details>:null}
    {workspace?<>
      <div className="scope-strip" data-testid="scope"><span><strong>{workspace.scope.examinedDeals} / {workspace.scope.totalDeals}</strong> {t('dealsRetrieved')}</span><span><strong>{workspace.scope.detailedDeals}</strong> {t('activityContext')}</span><span>{t('view',{type:workspace.type.charAt(0).toUpperCase()+workspace.type.slice(1)})}</span><Link href="/explore">{t('viewRecords')} <ArrowUpRight size={14}/></Link></div>
      <p className="scope-note">{workspace.scope.activityWindow} · {t('checked',{date:dateLabel(workspace.scope.checkedAt,locale)})} · {workspace.mode==='mock'?t('scriptedInterpretation'):t('liveInterpretation')}</p>
      {!workspace.items.length?<div className="empty-state"><SearchMark/><h2>{t('noMatching')}</h2><p>{t('nothingHidden')}</p><Button variant="outline" disabled={busy} onClick={()=>void run(focusPrompt)}>{t('reviewPriorities')}</Button><Link href="/explore">{t('openExplore')}</Link></div>:workspace.type==='focus'?<div className="situation-grid">{workspace.items.map(item=><SituationCard key={item.deal.id} item={item}/>)}</div>:workspace.type==='investigation'?<Investigation item={workspace.items[0]}/>:<Comparison items={workspace.items}/>}
      {workspace.proposal?<ActionCard proposal={workspace.proposal}/>:null}
    </>:!busy&&!runLoading?<div className="empty-state"><SearchMark/><h2>{t('startQuestion')}</h2><p>{t('startQuestionCopy')}</p><Button disabled={busy} onClick={()=>void run(focusPrompt)}>{t('reviewPriorities')} <ArrowRight size={16}/></Button></div>:null}
  </>;
}
function SearchMark(){return <div className="empty-mark"><FileText size={25}/></div>;}
function Investigation({item}:{item:WorkspaceItem}){const {workspace,run,busy}=useCrm();const {locale,t}=useLanguage();const taskPrompt=locale==='zh'?`为 ${item.customer.name} 创建跟进任务。`:`Create a follow-up task for ${item.customer.name}.`;return <>
  <section className="account-banner"><span className="account-monogram large">{item.customer.name.slice(0,1)}</span><div><h2>{item.customer.name}</h2><p>{item.customer.industry} · {item.deal.name}</p></div><div className="account-facts"><strong>{money(item.deal.value,locale)}</strong><span>{item.deal.stage} · {t('target',{date:dateLabel(item.deal.closeDate,locale)})}</span></div><Link href={`/explore?deal=${item.deal.id}`}>{t('openRecord')} <ArrowUpRight size={15}/></Link></section>
  <div className="investigation-grid"><section className="surface"><div className="section-heading"><h2>{t('recordsShow')}</h2><span className="small-label">{t('timeline')}</span></div><Timeline activities={item.timeline}/></section><div className="investigation-aside"><section className="surface"><Signal item={item}/><h2>{t('possibleNext')}</h2><Prose>{item.interpretation}</Prose><p className="small-label">{t('tentative')}</p>{!workspace?.proposal?<Button disabled={busy} onClick={()=>void run(taskPrompt,[item.deal.id])}>{t('prepareFollowUp')} <ArrowRight size={15}/></Button>:null}</section><section className="surface"><h2>{t('supportingEvidence')}</h2><EvidenceList activities={item.evidence}/></section></div></div>
  </>;}
function Comparison({items}:{items:WorkspaceItem[]}){const {locale,t}=useLanguage();return <section className="surface comparison-surface"><h2>{t('accountComparison')}</h2><div className="table-scroll" tabIndex={0} role="region" aria-label={t('accountComparison')}><table><caption className="sr-only">{t('sourceFacts')}</caption><thead><tr><th scope="col">{t('sourceFacts')}</th>{items.map(i=><th scope="col" key={i.deal.id}>{i.customer.name}</th>)}</tr></thead><tbody><tr><th scope="row">{t('dealValue')}</th>{items.map(i=><td key={i.deal.id}><strong>{money(i.deal.value,locale)}</strong></td>)}</tr><tr><th scope="row">{t('stage')}</th>{items.map(i=><td key={i.deal.id}>{i.deal.stage}</td>)}</tr><tr><th scope="row">{t('targetClose')}</th>{items.map(i=><td key={i.deal.id}>{dateLabel(i.deal.closeDate,locale)}</td>)}</tr><tr><th scope="row">{t('accountOwner')}</th>{items.map(i=><td key={i.deal.id}>{i.deal.owner}</td>)}</tr><tr><th scope="row">{t('interpretation')}</th>{items.map(i=><td key={i.deal.id}><Signal item={i}/><Prose>{i.interpretation}</Prose></td>)}</tr><tr><th scope="row">{t('evidence')}</th>{items.map(i=><td key={i.deal.id}><EvidenceList activities={i.evidence}/></td>)}</tr><tr><th scope="row">{t('inspect')}</th>{items.map(i=><td key={i.deal.id}><Link href={`/explore?deal=${i.deal.id}`}>{t('openRecord')} <ArrowUpRight size={13}/></Link></td>)}</tr></tbody></table></div></section>;}
