'use client';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,AlertTriangle,TrendingUp,Minus,CheckCircle2,LoaderCircle,FileText,Clock3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {useCrm} from './crm-provider';
import {ActionCard} from './action-card';
import {Prose} from './prose';
import {money,dateLabel} from '@/lib/format';
import type {Activity,WorkspaceItem} from '@/lib/contracts';
const signalLabels={attention:'Needs attention',opportunity:'Opportunity',watch:'Worth a closer look',neutral:'Recorded context'};
export function EvidenceList({activities}:{activities:Activity[]}){return <div className="evidence-list">{activities.length?activities.map(a=><div className="evidence-item" key={a.id}><FileText size={16}/><div><p>{a.text}</p><Link href={`/explore?tab=activities&deal=${encodeURIComponent(a.dealId)}#${a.id}`}>{dateLabel(a.at)} · {a.kind} · Source <ArrowUpRight size={12}/></Link></div></div>):<p className="small-label">No source evidence was returned for this record.</p>}</div>;}
export function Timeline({activities}:{activities:Activity[]}){return <ol className="timeline">{activities.length?activities.map(a=><li key={a.id}><span className="timeline-dot"/><div><time dateTime={a.at}>{dateLabel(a.at)}</time><strong>{a.kind==='task'?'Follow-up task':a.kind==='meeting'?'Customer meeting':a.kind==='email'?'Email recorded':'Account note'}</strong><p>{a.text}</p></div></li>):<li>No recorded activity.</li>}</ol>;}
function Signal({item}:{item:WorkspaceItem}){const Icon=item.signal==='attention'?AlertTriangle:item.signal==='opportunity'?TrendingUp:Minus;return <span className={`signal ${item.signal}`}><Icon size={14}/>{signalLabels[item.signal]}</span>;}
function SituationCard({item}:{item:WorkspaceItem}){const {run,busy}=useCrm();return <article className="situation-card"><div className="situation-top"><span className="account-monogram">{item.customer.name.slice(0,1)}</span><Signal item={item}/></div><h3>{item.customer.name}</h3><p className="deal-caption">{item.deal.name}</p><div className="deal-meta"><strong>{money(item.deal.value)}</strong><span>{item.deal.stage}</span></div><div className="interpretation"><span className="small-label">Interpretation · based on the records below</span><Prose>{item.interpretation}</Prose></div><EvidenceList activities={item.evidence.slice(0,2)}/><div className="card-actions"><Button variant="outline" disabled={busy} onClick={()=>void run(`What happened with ${item.customer.name}?`,[item.deal.id])}>Investigate {item.customer.name} <ArrowRight size={15}/></Button><Link href={`/explore?deal=${item.deal.id}`}>Record <ArrowUpRight size={14}/></Link></div></article>;}
export function WorkspacePage(){const {workspace,busy,runLoading,events,error,notice,run,clearError}=useCrm();const latest=events.at(-1);
  return <>
    <section className="page-heading compact"><div className="eyebrow">ADAPTIVE WORKSPACE</div><h1>{workspace?.title??'Your intent, a working view.'}</h1>{workspace?<Prose>{workspace.summary}</Prose>:<p>Ask a question below, or start with today’s priorities. The interface follows the task.</p>}</section>
    {error?<div className="notice error" role="alert"><div><strong>The latest request was not completed.</strong><p>{error}</p><Link href="/explore">Continue in Explore</Link></div><Button variant="ghost" onClick={clearError}>Dismiss</Button></div>:null}
    {notice?<p className="run-notice" role="status">{notice}</p>:null}
    {busy||runLoading?<div className="run-progress" role="status" aria-live="polite"><LoaderCircle className="spin" size={19}/><div><strong>{runLoading?'Loading saved workspace…':latest?`${latest.tool.replaceAll('_',' ')} · ${latest.status}`:'Starting the tool loop…'}</strong><span>Only completed tool events and verified source results are shown.</span></div></div>:null}
    {events.length?<details className="tool-trail"><summary><Clock3 size={15}/> Tool activity · {events.filter(e=>e.status==='succeeded').length} completed calls <span>Inspect execution</span></summary><div>{events.map((event,index)=><div className="tool-row" key={`${event.id}-${index}`}><span className={`tool-state ${event.status}`}>{event.status==='succeeded'?<CheckCircle2 size={15}/>:event.status==='running'?<LoaderCircle size={15}/>:<AlertTriangle size={15}/>}</span><code>{event.tool}</code><span>{event.status}</span><span>{event.detail}</span></div>)}</div></details>:null}
    {workspace?<>
      <div className="scope-strip" data-testid="scope"><span><strong>{workspace.scope.examinedDeals} / {workspace.scope.totalDeals}</strong> deals retrieved</span><span><strong>{workspace.scope.detailedDeals}</strong> with activity context</span><span>{workspace.type.charAt(0).toUpperCase()+workspace.type.slice(1)} view</span><Link href="/explore">View all records <ArrowUpRight size={14}/></Link></div>
      <p className="scope-note">{workspace.scope.activityWindow} · Checked {dateLabel(workspace.scope.checkedAt)} · {workspace.mode==='mock'?'Scripted interpretation, not a live LLM':'Live model interpretation'}</p>
      {!workspace.items.length?<div className="empty-state"><SearchMark/><h2>No matching analysis to display.</h2><p>Nothing is being hidden or replaced. Try a supported request or inspect the full dataset.</p><Button variant="outline" disabled={busy} onClick={()=>void run('What should I focus on today?')}>Review today’s priorities</Button><Link href="/explore">Open Explore</Link></div>:workspace.type==='focus'?<div className="situation-grid">{workspace.items.map(item=><SituationCard key={item.deal.id} item={item}/>)}</div>:workspace.type==='investigation'?<Investigation item={workspace.items[0]}/>:<Comparison items={workspace.items}/>}
      {workspace.proposal?<ActionCard proposal={workspace.proposal}/>:null}
    </>:!busy&&!runLoading?<div className="empty-state"><SearchMark/><h2>Start with a business question.</h2><p>A focus list, an account investigation, or a comparison—not another chat transcript.</p><Button disabled={busy} onClick={()=>void run('What should I focus on today?')}>Review today’s priorities <ArrowRight size={16}/></Button></div>:null}
  </>;
}
function SearchMark(){return <div className="empty-mark"><FileText size={25}/></div>;}
function Investigation({item}:{item:WorkspaceItem}){const {workspace,run,busy}=useCrm();return <>
  <section className="account-banner"><span className="account-monogram large">{item.customer.name.slice(0,1)}</span><div><h2>{item.customer.name}</h2><p>{item.customer.industry} · {item.deal.name}</p></div><div className="account-facts"><strong>{money(item.deal.value)}</strong><span>{item.deal.stage} · Target {dateLabel(item.deal.closeDate)}</span></div><Link href={`/explore?deal=${item.deal.id}`}>Open record <ArrowUpRight size={15}/></Link></section>
  <div className="investigation-grid"><section className="surface"><div className="section-heading"><h2>What the records show</h2><span className="small-label">Timeline</span></div><Timeline activities={item.timeline}/></section><div className="investigation-aside"><section className="surface"><Signal item={item}/><h2>Possible next step</h2><Prose>{item.interpretation}</Prose><p className="small-label">This is an interpretation—not a confirmed customer decision.</p>{!workspace?.proposal?<Button disabled={busy} onClick={()=>void run(`Create a follow-up task for ${item.customer.name}.`,[item.deal.id])}>Prepare follow-up task <ArrowRight size={15}/></Button>:null}</section><section className="surface"><h2>Supporting evidence</h2><EvidenceList activities={item.evidence}/></section></div></div>
  </>;}
function Comparison({items}:{items:WorkspaceItem[]}){return <section className="surface comparison-surface"><h2>Account comparison</h2><div className="table-scroll" tabIndex={0} role="region" aria-label="Account comparison table"><table><caption className="sr-only">Source-backed deal facts and separately labelled interpretation</caption><thead><tr><th scope="col">Source facts</th>{items.map(i=><th scope="col" key={i.deal.id}>{i.customer.name}</th>)}</tr></thead><tbody><tr><th scope="row">Deal value</th>{items.map(i=><td key={i.deal.id}><strong>{money(i.deal.value)}</strong></td>)}</tr><tr><th scope="row">Stage</th>{items.map(i=><td key={i.deal.id}>{i.deal.stage}</td>)}</tr><tr><th scope="row">Target close</th>{items.map(i=><td key={i.deal.id}>{dateLabel(i.deal.closeDate)}</td>)}</tr><tr><th scope="row">Account owner</th>{items.map(i=><td key={i.deal.id}>{i.deal.owner}</td>)}</tr><tr><th scope="row">Interpretation</th>{items.map(i=><td key={i.deal.id}><Signal item={i}/><Prose>{i.interpretation}</Prose></td>)}</tr><tr><th scope="row">Evidence</th>{items.map(i=><td key={i.deal.id}><EvidenceList activities={i.evidence}/></td>)}</tr><tr><th scope="row">Inspect</th>{items.map(i=><td key={i.deal.id}><Link href={`/explore?deal=${i.deal.id}`}>Open {i.customer.name} record <ArrowUpRight size={13}/></Link></td>)}</tr></tbody></table></div></section>;}
